spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  hazelcast:
    config: file:/Users/nklkarthi/github-projects/nklkarthi/pbcache-spring-boot/config/hazelcast-dev.xml

---

spring:
  profiles: sit
  hazelcast:
    config: file:/Users/nklkarthi/github-projects/nklkarthi/pbcache-spring-boot/config/hazelcast-sit.xml

---
spring:
  profiles: uat
  hazelcast:
    config: file:/Users/nklkarthi/github-projects/nklkarthi/pbcache-spring-boot/config/hazelcast-uat.xml

---

spring:
  profiles: prod
  hazelcast:
    config: file:/Users/nklkarthi/github-projects/nklkarthi/pbcache-spring-boot/config/hazelcast-prod.xml



