spring:
  profiles.active: dev

---
spring:
  profiles: dev
hazelcast-settings:
  ip: 127.0.0.1
  port: 7001

---
spring:
   profiles: unit-test
hazelcast-settings:
  ip: 127.0.0.1
  port: 8001

---
spring:
   profiles: sit
hazelcast-settings:
  ip: 127.0.0.1
  port: 9001

